heat_template_version: 2013-05-23

description: |
  Heat Template to deploy a Couchbase cluster

parameters:
  key_name:
    type: string
    default: my_key
  public_network:
    type: string
    default: external
  private_network:
    type: string
    default: tenant
  image_name:
    type: string
    default: rhel72
  flavor:
    type: string
    default: m1.small
  num_data_instances:
    type: number
    description: Number of Couchbase data node instances to create
    default: 2

resources:
  cb_cluster_main:
    type: OS::Nova::Server
    properties:
      name: couchbase-main
      image: { get_param: image_name }
      flavor: { get_param: flavor }
      key_name: {get_param: key_name }
      networks:
        - port: { get_resource: cb_cluster_main_port }
      user_data_format: RAW
      user_data: |
          #!/bin/bash -ex
          echo "Hello from couchbase-main Updated" > /tmp/server_hello

  cb_cluster_main_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network }

  cb_cluster_main_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_network }
      port_id: { get_resource: cb_cluster_main_port }

  cb_cluster_data_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_data_instances }
      resource_def:
         type: RH::Server::Couchbase
         properties:
           key_name: { get_param: key_name }
           image: { get_param: image_name }
           flavor: { get_param: flavor }
           public_network: { get_param: private_network }
           private_network: { get_param: private_network }

outputs:
  cb_cluster_main_floating_ip:
    description: Floating IP address of cb_cluster_main instance
    value: { get_attr: [cb_cluster_main_floating_ip, floating_ip_address ] }
  cb_cluster_main_private_ip:
    description: Private IP address of cb_cluster_main instance
    value: { get_attr: [cb_cluster_main, first_address ] }
  cb_cluster_data_group_ips:
    description: Private IP addresses for all of the data nodes
    value: { get_attr: [cb_cluster_data_group, resources, first_address] }
