heat_template_version: 2013-05-23

description: |
  The heat template is used to demo the 'console_urls' attribute
  of OS::Nova::Server.

parameters:
  image:
    type: string
    default: rhel72
  flavor:
    type: string
    default: m1.medium

resources:
  serverX:
    type: OS::Nova::Server
    properties:
      name: CouchbaseServer1
      image: rhel72
      flavor: m1.medium
      key_name: kejones
      networks:
        - port: { get_resource: serverX_port }
      user_data_format: RAW
      user_data: |
          #!/bin/bash -ex
          echo "Hello from SERVER X Updated" > /tmp/server_hello

  serverX_port:
    type: OS::Neutron::Port
    properties:
      network_id: tenant

  serverX_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: external
      port_id: { get_resource: serverX_port }

  serverY:
    type: OS::Nova::Server
    properties:
      name: CouchbaseServer2
      image: rhel72
      flavor: m1.medium
      key_name: kejones
      networks:
        - port: { get_resource: serverY_port }
      user_data_format: RAW
      user_data: |
          #!/bin/bash -ex
          echo "Hello from SERVER Y Updated" > /tmp/server_hello

  serverY_port:
    type: OS::Neutron::Port
    properties:
      network_id: tenant

  serverY_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: external
      port_id: { get_resource: serverY_port }

  serverZ:
    type: OS::Nova::Server
    properties:
      name: CouchbaseServer3
      image: rhel72
      flavor: m1.medium
      key_name: kejones
      networks:
        - port: { get_resource: serverZ_port }

  serverZ_port:
    type: OS::Neutron::Port
    properties:
      network_id: tenant

  serverZ_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: external
      port_id: { get_resource: serverZ_port }

outputs:
  Couchbase1_Floating_IP:
    description: Floating IP address of serverX instance
    value: { get_attr: [serverX_floating_ip, floating_ip_address ] }
  Couchbase2_Floating_IP:
    description: Floating IP address of serverY instance
    value: { get_attr: [serverY_floating_ip, floating_ip_address ] }
  Couchbase3_Floating_IP:
    description: Floating IP address of serverZ instance
    value: { get_attr: [serverZ_floating_ip, floating_ip_address ] }
  Couchbase1_Private_IP:
    description: Private IP address of serverX instance
    value: { get_attr: [serverX, first_address ] }
  Couchbase2_Private_IP:
    description: Private IP address of serverY instance
    value: { get_attr: [serverY, first_address ] }
  Couchbase3_Private_IP:
    description: Private IP address of serverZ instance
    value: { get_attr: [serverZ, first_address ] }
