---
# Install Couchbase cluster
- name: Couchbase Installation
  hosts: all
  user: cloud-user
  become: true
  tasks:
  - name: Download couchbase rpm to server
    get_url:
      url: https://github.com/redhat-kejones/couchbase-heat-ansible/blob/master/software/couchbase-server-community-4.1.0-centos7.x86_64.rpm?raw=true
      dest: /tmp/couchbase-server-community-4.1.0-centos7.x86_64.rpm
  - name: Install couchbase rpm
    yum:
       name: /tmp/couchbase-server-community-4.1.0-centos7.x86_64.rpm
       state: present
  - name: Ensure couchbase-server.service is started
    service: name=couchbase-server.service state=started

