---
# Config Couchbase nodes
- name: Config couchbase nodes
  hosts: all
  user: cloud-user
  become: true
  tasks:
  - name: Create shell script for configuring main node
    action: template src=templates/couchbase-add-node.j2 dest=/tmp/addnodes.sh mode=750

  - name: Launch config script
    action: shell /tmp/addnodes.sh
  
  - name: Rebalance the cluster
    shell: /opt/couchbase/bin/couchbase-cli rebalance -c {{ cluster_main_ip }}:8091 -u {{ admin_user }} -p {{ admin_password }}
